### ISSUE TITLE
Fine Tuning of totalsegmentator

### ISSUE THREAD

**Issue by MatteoFusconi** [AntonZhitomirsky/radiotherapy#1]
Hello, first of all I want to thank you for your amazing work, and for making it available.
I am a student of the university of Bologna, and for a project exam, I have to fine-tune TotalSegmentator using few data of femurs.

Since there is not a lot of documentation on fine tuning TotalSegmentator, I was using your code on radiotherapy/research/source/code/totalsegmentator for guidance.

running the functions in 0_plans_and_preprocess_data, it seems that there are some environment variables that are set somewhere, but not in data_vars.sh (maybe in the /venv/bin/activate?)
```
classes = [os.environ.get('Anorectum')
             , os.environ.get('Bladder') 
             , os.environ.get('CTVn') 
             , os.environ.get('CTVp') 
             , os.environ.get('Parametrium') 
             , os.environ.get('Uterus') 
             , os.environ.get('Vagina')
             , os.environ.get('TotalBinary')
             , os.environ.get('TotalSegmentator')]
```

I wish you could help me in how are those variables set, especially 'TotalSegmentator'?

Thank you in advance, and sorry for the disturb

**Comment by avzh1** [comment]
Hi, sorry for the late reply!

Of course, I can help.

The context of my work, is that I am working with 7 classes. These are stored in the nnunet format in `data/nnUNet_raw/Dataset001_Anorectum` for example. 

In my `data_vars.sh` script I set up the script to dynamically set whatever variables appeared:

```
# assume we have an nnUNet_raw folder. Therefore, inside we have the different organ
# classes. Get names of all directories present in nnUNet_raw and export them
for dir in $(find $nnUNet_raw -maxdepth 1 -type d ! -name "$(basename $nnUNet_raw)"); do
    IFS="_" read -ra parts <<< "$(basename $dir)"
    # access the parts of the string using ${parts[index]}
    export ${parts[1]}="$(basename $dir)"
    # add new environment variable to list
    new_env_vars+=(${parts[1]})
done
```
(meaning, if i see `Dataset001_Anorectum` then I'll get an environmnet variable called `Anorectum := path/to/Dataset001_Anorectum`)


Therefore, these environment variables refer to the datasets present in nnunet_raw. Feel free to replace them with your own, the program should run with them also.

As for TotalSegmentator environmnet variable, this was a dummy folder I created. I copied over the `plans` file that I donwloaded form the totalsegmentator and put it there.

Good luck with your university project!
